version: '3.8'

services:
  app:
    build: .
    container_name: hrm_app
    restart: always
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    environment:
      - TERM=xterm
    # Aplikasi akan connect ke database eksternal melalui host VPS (misal: localhost VPS / IP DB container exisiting)
